export const mockAbstracts = [
	{
		id: '1',
		title: 'Advanced Retinal Imaging Techniques',
		introduction: 'A study on modern imaging methods in ophthalmology...',
		theme: 'Imaging',
		type: 'oral',
		status: 'approved',
		created_at: '2024-01-15T10:00:00Z',
		co_authors: ['Dr. Jane Smith', 'Dr. John Doe'],
	},
	{
		id: '2',
		title: 'New Treatments for Glaucoma',
		introduction: 'Investigating novel approaches to glaucoma management...',
		theme: 'Glaucoma',
		type: 'poster',
		status: 'reviewing',
		created_at: '2024-01-20T14:30:00Z',
		co_authors: ['Dr. Alice Johnson'],
	},
	{
		id: '3',
		title: 'Corneal Transplantation Outcomes',
		introduction: 'Long-term study of corneal transplant success rates...',
		theme: 'Cornea',
		type: 'oral',
		status: 'final-version',
		created_at: '2024-01-18T09:15:00Z',
		co_authors: ['Dr. Robert Wilson', 'Dr. Emma Brown'],
	},
	{
		id: '4',
		title: 'Pediatric Vision Screening',
		introduction: 'Early detection methods for childhood vision problems...',
		theme: 'Pediatrics',
		type: 'poster',
		status: 'submitted',
		created_at: '2024-01-22T16:45:00Z',
		co_authors: ['Dr. Sarah Chen'],
	},
	{
		id: '5',
		title: 'Diabetic Retinopathy Prevention',
		introduction:
			'New strategies in preventing diabetic retinopathy progression...',
		theme: 'Retina',
		type: 'oral',
		status: 'type-change',
		created_at: '2024-01-19T11:20:00Z',
		co_authors: ['Dr. Michael Lee', 'Dr. David Park'],
	},
	{
		id: '6',
		title: 'Cataract Surgery Innovations',
		introduction: 'Recent advances in cataract surgical techniques...',
		theme: 'Surgery',
		type: 'poster',
		status: 'approved',
		created_at: '2024-01-21T13:10:00Z',
		co_authors: ['Dr. Lisa Anderson'],
	},
	{
		id: '7',
		title: 'Myopia Management in Children',
		introduction: 'Comparative study of myopia control methods...',
		theme: 'Pediatrics',
		type: 'oral',
		status: 'reviewing',
		created_at: '2024-01-17T15:30:00Z',
		co_authors: ['Dr. Tom Harris', 'Dr. Julia Martinez'],
	},
	{
		id: '8',
		title: 'Dry Eye Disease Treatment',
		introduction: 'Evaluation of new therapeutic approaches for dry eye...',
		theme: 'Ocular Surface',
		type: 'poster',
		status: 'rejected',
		created_at: '2024-01-16T10:45:00Z',
		co_authors: ['Dr. Rachel Green'],
	},
	{
		id: '9',
		title: 'Gene Therapy in Retinal Disease',
		introduction:
			'Progress in genetic treatments for inherited retinal disorders...',
		theme: 'Genetics',
		type: 'oral',
		status: 'final-version',
		created_at: '2024-01-23T09:00:00Z',
		co_authors: ['Dr. James Wilson', 'Dr. Karen White'],
	},
];
